use bms;
CREATE TABLE CONTACT(
    CONTACT_CD INT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID VARCHAR(20) ,
    EMAIL VARCHAR(30) ,
    MESSAGE VARCHAR(600) ,
    ENROLL_DT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    RESOLVED BOOLEAN DEFAULT FALSE
);